### ISSUE TITLE
Specs fail for path parameters which are not required but do have a regex pattern

### ISSUE THREAD

**Issue by jandouwebeekman** [skryukov/json_skooma#12]
It appears as if the validator will always try to validate path parameters even if they are not required

I have an endpoint with the following parameter:

```
      parameters:
      - name: format
        in: path
        required: false
        schema:
          type: string
          pattern: '.(xml|json)'
```

This means that the format can also be an empty string because it is not required
When I use Skooma to validate my request I get the error

`"error" => "The text must match the regular expression .(xml|json)"`

This issue will be hard to replicate as when you want to validate a request with Skooma, it will try to match the request to an endpoint where each path paramater should follow "[^/?#]+", meaning a path parameter currently can never be an empty string.
I am working on a fork of Skooma to make sure the validator would match requests to endpoints on a regex of "(.(xml|json))?" instead of "[^/?#]+", and that is why I encountered this bug.

This is not a breaking issue because you can easily not use the 'required' field and use a "( ... )?" in the regex pattern if it is not required
